name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-plan:
    name: Test and Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install flake8

    - name: Lint with flake8
      run: flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./terraform
      env:
        TF_VAR_meili_url: ${{ secrets.MEILI_URL }}
        TF_VAR_meili_api_key: ${{ secrets.MEILI_API_KEY }}

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test-and-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply --auto-approve
      working-directory: ./terraform
      env:
        TF_VAR_meili_url: ${{ secrets.MEILI_URL }}
        TF_VAR_meili_api_key: ${{ secrets.MEILI_API_KEY }} 